package com.senac.swing;


import com.senac.ws.Pedido;
import java.awt.Image;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class TerminalAtendimento extends javax.swing.JFrame {
    private Pedido pedido;
    private static boolean habilitarBtnNextPedido;

    /**
     * Creates new form TerminalAtendimento
     */
    public TerminalAtendimento() {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
            Image i = ImageIO.read(getClass().getResource("img/french_fries.png"));
            setIconImage(i);
        } catch (IOException ex) {
            Logger.getLogger(TerminalAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        btnFinalizarPedido.setEnabled(false);
        habilitarBtnNextPedido = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedido = new javax.swing.JTextArea();
        btnNextPedido = new javax.swing.JButton();
        btnFinalizarPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFilaPedidos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atendimento");
        setResizable(false);

        txtPedido.setEditable(false);
        txtPedido.setColumns(20);
        txtPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPedido.setRows(5);
        jScrollPane1.setViewportView(txtPedido);

        btnNextPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNextPedido.setText("Próximo Pedido");
        btnNextPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPedidoActionPerformed(evt);
            }
        });

        btnFinalizarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pedido");

        txtFilaPedidos.setEditable(false);
        txtFilaPedidos.setColumns(20);
        txtFilaPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFilaPedidos.setRows(5);
        jScrollPane2.setViewportView(txtFilaPedidos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fila de Pedidos");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/senac/swing/img/fast_food.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnNextPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNextPedido)
                            .addComponent(btnFinalizarPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPedidoActionPerformed
        try {
            pedido = solicitarPedido();
        
            txtPedido.append("Pedido: " + pedido.getNumero() + "\n");
            btnNextPedido.setEnabled(false);
            btnFinalizarPedido.setEnabled(true);
            habilitarBtnNextPedido = false;

            for (int i = 0; i < pedido.getItensPedido().size(); i++) {
                txtPedido.append(pedido.getItensPedido().get(i).getCodigo() + " - " + 
                        pedido.getItensPedido().get(i).getDescricao() + "\n");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnNextPedidoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        String retorno;
        
        try {
            retorno = fecharPedido(pedido.getNumero());
            txtPedido.setText("");
            btnFinalizarPedido.setEnabled(false);
            btnNextPedido.setEnabled(true);
            habilitarBtnNextPedido = true;
            JOptionPane.showMessageDialog(this, retorno);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed
    
    
    
    private static void atualizarListaPedidos() {
        List<Pedido> filaPedidos;
                
        while (true) {
            filaPedidos = buscarFilaPedidos();
            
            if (!filaPedidos.isEmpty() && habilitarBtnNextPedido) {
                btnNextPedido.setEnabled(true);
            } else {
                btnNextPedido.setEnabled(false);
            }
            
            txtFilaPedidos.setText("");

            for (Pedido pedido : filaPedidos) {
                txtFilaPedidos.append("Pedido: " + pedido.getNumero() + "\n");

                for (int i = 0; i < pedido.getItensPedido().size(); i++) {
                        txtFilaPedidos.append(pedido.getItensPedido().get(i).getCodigo() + " - " +
                                        pedido.getItensPedido().get(i).getDescricao() + "\n");
                }
                
                txtFilaPedidos.append("\n");
            }
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(TerminalAtendimento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private static java.util.List<com.senac.ws.Pedido> buscarFilaPedidos() {
        com.senac.ws.ServidorCantinaWS_Service service = new com.senac.ws.ServidorCantinaWS_Service();
        com.senac.ws.ServidorCantinaWS port = service.getServidorCantinaWSPort();
        return port.buscarFilaPedidos();
    }

    private static Pedido solicitarPedido() {
        com.senac.ws.ServidorCantinaWS_Service service = new com.senac.ws.ServidorCantinaWS_Service();
        com.senac.ws.ServidorCantinaWS port = service.getServidorCantinaWSPort();
        return port.solicitarPedido();
    }

    private static String fecharPedido(java.lang.Integer numeroPedido) {
        com.senac.ws.ServidorCantinaWS_Service service = new com.senac.ws.ServidorCantinaWS_Service();
        com.senac.ws.ServidorCantinaWS port = service.getServidorCantinaWSPort();
        return port.fecharPedido(numeroPedido);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminalAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminalAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminalAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminalAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerminalAtendimento().setVisible(true);
            }
        });
        
        atualizarListaPedidos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnFinalizarPedido;
    private static javax.swing.JButton btnNextPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private static javax.swing.JTextArea txtFilaPedidos;
    private javax.swing.JTextArea txtPedido;
    // End of variables declaration//GEN-END:variables

}
