
import com.senac.ws.Pedido;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TerminalAtendimento extends javax.swing.JFrame {
    private Pedido pedido;

    /**
     * Creates new form TerminalAtendimento
     */
    public TerminalAtendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedido = new javax.swing.JTextArea();
        btnNextPedido = new javax.swing.JButton();
        btnFinalizarPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFilaPedidos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atendimento");

        txtPedido.setEditable(false);
        txtPedido.setColumns(20);
        txtPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPedido.setRows(5);
        jScrollPane1.setViewportView(txtPedido);

        btnNextPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNextPedido.setText("Próximo Pedido");
        btnNextPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPedidoActionPerformed(evt);
            }
        });

        btnFinalizarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pedido");

        txtFilaPedidos.setEditable(false);
        txtFilaPedidos.setColumns(20);
        txtFilaPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFilaPedidos.setRows(5);
        jScrollPane2.setViewportView(txtFilaPedidos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fila de Pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNextPedido))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNextPedido)
                            .addComponent(btnFinalizarPedido))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPedidoActionPerformed
        pedido = solicitarPedido();
        
        txtPedido.append("Pedido: " + pedido.getNumero() + "\n");
        
        for (int i = 0; i < pedido.getItensPedido().size(); i++) {
            txtPedido.append(pedido.getItensPedido().get(i).getCodigo() + " - " + 
                    pedido.getItensPedido().get(i).getDescricao() + "\n");
        }
    }//GEN-LAST:event_btnNextPedidoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        fecharPedido(pedido.getNumero());
        txtPedido.setText("");
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed
    
    private static void atualizarListaPedidos() {
        List<Pedido> filaPedidos;
                
        while (true) {
            filaPedidos = buscarFilaPedidos();
            
            txtFilaPedidos.setText("");

            for (Pedido pedido : filaPedidos) {
                txtFilaPedidos.append("Pedido: " + pedido.getNumero() + "\n");

                for (int i = 0; i < pedido.getItensPedido().size(); i++) {
                        txtFilaPedidos.append(pedido.getItensPedido().get(i).getCodigo() + " - " +
                                        pedido.getItensPedido().get(i).getDescricao() + "\n");
                }
                
                txtFilaPedidos.append("\n");
            }
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(TerminalAtendimento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminalAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminalAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminalAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminalAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerminalAtendimento().setVisible(true);
            }
        });
        
        atualizarListaPedidos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnNextPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea txtFilaPedidos;
    private javax.swing.JTextArea txtPedido;
    // End of variables declaration//GEN-END:variables

    private static void fecharPedido(java.lang.Integer numeroPedido) {
        com.senac.ws.ServidorCantinaWS_Service service = new com.senac.ws.ServidorCantinaWS_Service();
        com.senac.ws.ServidorCantinaWS port = service.getServidorCantinaWSPort();
        port.fecharPedido(numeroPedido);
    }

    private static Pedido solicitarPedido() {
        com.senac.ws.ServidorCantinaWS_Service service = new com.senac.ws.ServidorCantinaWS_Service();
        com.senac.ws.ServidorCantinaWS port = service.getServidorCantinaWSPort();
        return port.solicitarPedido();
    }

    private static java.util.List<com.senac.ws.Pedido> buscarFilaPedidos() {
        com.senac.ws.ServidorCantinaWS_Service service = new com.senac.ws.ServidorCantinaWS_Service();
        com.senac.ws.ServidorCantinaWS port = service.getServidorCantinaWSPort();
        return port.buscarFilaPedidos();
    }

}
